ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_reservist BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS city TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS driver_license BOOLEAN DEFAULT FALSE;
