ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS first_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS first_name_en TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_name_en TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cover_letter TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS available_start_date DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS desired_salary TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS work_authorized BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS requires_sponsorship BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS race_ethnicity TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS veteran_status TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS disability_status TEXT DEFAULT NULL;
